### ISSUE TITLE
How's it going?

### ISSUE THREAD

**Issue by katieannemills** [schae234/studyGroup#1]
Hey @schae234, how are things going with your new Study Group? I'm happy to help in any way I can, and would be delighted for feedback - throw anything you'd like to talk about onto our [issues](https://github.com/mozillascience/studyGroup/issues), or get me privately at bill@mozillafoundation.org - thanks for checking things out!

**Comment by schae234** [comment]
Hi @BillMills , things are moving slowly, but surely. We are still trying to figure out how this might fit into our own lab. We study biology with a mix of computational approaches and are looking for new ways to organize and connect with one another. We have not had success in the past with 'tutorial' style classes, so we think here that we might be able to have a more distributed based study group -- perfect for some thing like github. As we get started, we will be sure to let you know how things are going and ask questions as they arise.

**Comment by katieannemills** [comment]
Sounds good. I'd love to learn more about your experiences with tutorials that wasn't so great - if it didn't work for you, then it's not working for plenty of other people, too. Maybe a [co-working](http://mozillascience.github.io/studyGroupHandbook/events.html#coworking) or [code review](http://mozillascience.github.io/codeReview/review.html#team) style session would work better?

**Comment by schae234** [comment]
It seems like when we organize a coding tutorial there are two clear groups, beginners and advanced students. The beginners just become frustrated because it takes a long time to learn anything they are going to find useful in their research and the advanced group feels like they are wasting their time because they can learn about for-loops or whatever on google. People don't want to learn how to become super awesome programmers, they want just enough to solve their problems, so maybe we've had it wrong all along trying to evangelize researchers into becoming programmers. 

I was hoping to use this as something that we could focus in directly in our lab. I would like to have a place where we could focus on day to day problems people in the lab actually have with coding and solve them as a group. The StudyGroup looked tantalizing because it has a very nice base for sharing information and I think if we do it right, we can trick people into using github more instead of emailing back and forth about issues that they are having. 

If we have people submit small tasks to the github issues area, we can solve it in a distributed way via the forums on github and then have the meeting focus on recapping instead of trying to shove everything into a one hour super session.

Sorry if this is nebulous, but like I said, we are just playing around with this as a platform. Does this at all fit into the vision you have for StudyGroup?

**Comment by katieannemills** [comment]
This is an awesome idea; so much awesome, I'm not sure where to start. A few observations:
- You're absolutely right that trying to lead researchers into becoming expert programmers is a waste of energy; it's really not necessary. What I would like to see, however, is researchers becoming fluent with basic best practices (write functions; use version control; publish your code; reuse your code and code from others). All of which boils down to writing for reuse, which has some basic skills associated with it.
- In the same vein, some of the best Study Group lessons have been ones that are basically a 'show and tell' of a new package, illustrating how it can be used in relevant research. Then the lesson is less about expert knowledge, and more about discovering a new tool, which is a consistently hard and unsolved problem.

Your idea of convening a Study Group to address the day to day problems people are having is an excellent one; ultimately, Study Groups are less about exactly how people share knowledge and work together, and more about they _do that_ by any means appealing to them. So yes! Not only would I love to see you give it a go, I'd love to hear about how you do it and how it turns out; I think this idea could be really valuable to the wider community.

**Comment by schae234** [comment]
Hi again @BillMills,

I met with a a collaborator today to discuss this idea of using a studyGroup as a sort of decentralized, repository based platform for organizing code and efforts on the lab. She was very excited about it! I am going to schedule out first 'meeting' very soon, it'll likely revolve around goals of the studyGroup and how we can make sure it gets used to its full potential. I think we will start with principles of git and get everyone to sign up and create an account, make sure they enable the Issues feature, etc.

We also got to talking about how web based methods of scientific collaboration would fit into our current research pipeline. We've been playing around with other digital organizational  electronic lab notebooks and citation software both of which have available APIs. We want to explore some of these things further, so I'm planning on participating in the Code Sprint coming up and try hacking on making these things easier to use for us, possibly as a plugin or something for studyGroup. Sounds like a good way to start getting involved.

Hopefully, more to come soon.

**Comment by katieannemills** [comment]
Nice, I like the sprint proposal; before the date, let us know some details on how people can get involved there (repo with issues / contrib guidelines, or a listing on [Collaborate](http://www.mozillascience.org/collaborate/)), and what you'd like to focus on. Just ping me if I can help!

**Comment by schae234** [comment]
Lets close this thread now so new participants will not be confused on what is going on. We are having our first meeting later this week so we can re-open a thread later on to check it ;)
